services:
  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 4306:3306
    volumes:
      - db_data:/var/lib/mysql
  
  backend:
    tty: true
    depends_on:
      - db
      - redis  
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./back:/back
      - gem_data:/usr/local/bundle
    command: bundle exec rails server -b 0.0.0.0 -p 3000  
  
  frontend:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/my-app:/usr/src/app
    command: "yarn dev"
    ports:
      - "8000:3000"
  
  redis:
    image: redis:6.2
    ports:
      - 6379:6379 
    volumes:
      - redis_data:/data

volumes:
  db_data:
  gem_data:
  redis_data:
