development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: back_development

test:
  adapter: redis
  url: redis://redis:6379/0
  channel_prefix: back_test

production:
  adapter: redis
  url: rediss://<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT']%>/0
  channel_prefix: myapp_production
  ssl_params: { verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %> }
