development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: back_development

test:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: back_test

production:
  adapter: redis
  url: rediss://redis-elasticache-vpwoxv.serverless.apne1.cache.amazonaws.com:6379/0
  channel_prefix: back_production
  ssl: true
  ssl_params:
    verify_mode: "none"
