development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: back_development

test:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: back_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>
  channel_prefix: back_production
