development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: back_development

test:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: back_test

production:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] %>:6379/1
  channel_prefix: back_production
