inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  # 結果のsuggest部分を非表示
  SuggestExtensions: false
  #最新のルールを適用
  NewCops: enable
  #何のルールに引っかかったか表示
  DisplayCopNames: true
  # 自動生成されるファイルは基本的に除外
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "public/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "bin/*"
    - "config/environments/*"
    - "config/puma.rb"

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# ユーザーパスワードとパスワード確認のバリデーションをスキップする必要があるため、update_attributeの使用を許可
Rails/SkipsModelValidations:
  Exclude:
    - "app/models/user.rb"

# インスタンス変数を許可
Rails/HelperInstanceVariable:
  Exclude:
    - "app/helpers/sessions_helper.rb"

# Requestsテストは行数規定を除外
RSpec/ExampleLength:
  Exclude:
    - "spec/requests/users_spec.rb"
    - "spec/requests/relationships_spec.rb"
    - "spec/requests/sessions_spec.rb"

# テスト文言は日本語とするため除外
RSpec/ContextWording:
  Exclude:
    - "spec/requests/*.rb"

# request specは複数のexpectationsを許可する
RSpec/MultipleExpectations:
  Exclude:
    - "spec/requests/*.rb"

# インスタンス変数を許可
RSpec/InstanceVariable:
  Exclude:
    - "spec/requests/relationships_spec.rb"
