# 残りは全てusers_controller.rbの記述
# この設定は`rubocop --auto-gen-config`によって2024-06-07 15:12:13 UTCに
# 生成されました。使用されているRuboCopのバージョンは1.63.3です。
# ポイントは、ユーザーがコードベースから違反を削除するにつれて、これらの設定レコードを
# 一つずつ削除することにあります。
# 注意すべき点は、検査対象のコードの変更や新しいバージョンのRuboCopのインストールにより
# このファイルを再生成する必要があるかもしれないということです。

# 違反数: 3
# 設定パラメータ: AllowedMethods, AllowedPatterns, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 32

# 違反数: 1
# 設定パラメータ: CountComments, CountAsOne.
Metrics/ClassLength:
  Max: 156

# 違反数: 4
# 設定パラメータ: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 24

# 違反数: 5
# このコップは安全な自動修正（--autocorrect）をサポートします。
# 設定パラメータ: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, AllowedPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 142
