# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0'

gem 'bcrypt', '~> 3.1.18'
gem 'bootsnap', '~> 1.18.3', require: false
gem 'carrierwave', '~> 2.2.6'
gem 'faker', '~> 2.21.0'
gem 'image_processing', '~> 1.12.2'
gem 'importmap-rails', '~> 1.1.5'
gem 'jbuilder', '~> 2.11.5'
gem 'kaminari', '~> 1.2.2'
gem 'mysql2', '~> 0.5.6'
gem 'puma', '~> 5.6.5'
gem 'rack-cors', '~> 2.0.2', require: 'rack/cors'
gem 'rails', '~> 7.0.4.3'
gem 'sassc-rails', '~> 2.1.2'
gem 'sprockets-rails', '~> 3.4.2'
gem 'stimulus-rails', '~> 1.2.1'
gem 'turbo-rails', '~> 1.4.0'

group :production do
  gem 'aws-sdk-s3', '~> 1.114.0', require: false
end

group :development, :test do
  gem 'debug', '~> 1.7.1', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '~> 6.4.3'
  gem 'rake', '~> 13.2.1'
  gem 'rspec-rails', '~> 6.1.3'
  gem 'spring-commands-rspec', '~> 1.0.4'
end

group :development do
  gem 'bullet', '~> 7.1.6'
  gem 'rubocop', '~> 1.65.0', require: false
  gem 'rubocop-performance', '~> 1.21.1', require: false
  gem 'rubocop-rails', '~> 2.25.1', require: false
  gem 'rubocop-rspec', '~> 3.0.2', require: false
  gem 'solargraph', '~> 0.48.0'
  gem 'web-console', '~> 4.2.0'
end

group :test do
  gem 'capybara', '~> 3.38.0'
  gem 'guard', '~> 2.18.0'
  gem 'mock_redis', '~> 0.44.0'
  gem 'rails-controller-testing', '~> 1.0.5'
  gem 'selenium-webdriver', '~> 4.8.3'
  gem 'webdrivers', '~> 5.2.0'
end

gem 'redis', '~> 5.2.0'
gem 'retryable', '~> 3.0.5'
