# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0'

gem 'bcrypt', '3.1.18'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'carrierwave', '~> 2.0'
gem 'faker', '2.21.0'
gem 'image_processing', '1.12.2'
gem 'importmap-rails', '1.1.5'
gem 'jbuilder', '2.11.5'
gem 'kaminari', '~> 1.2.2'
gem 'mysql2', '~> 0.5.6'
gem 'puma', '5.6.5'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '7.0.4.3'
gem 'sassc-rails', '2.1.2'
gem 'sprockets-rails', '3.4.2'
gem 'stimulus-rails', '1.2.1'
gem 'turbo-rails', '1.4.0'

group :production do
  gem 'aws-sdk-s3', '1.114.0', require: false
end

group :development, :test do
  gem 'debug', '1.7.1', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'rake', '~> 13.0'
  gem 'rspec-rails', '~> 6.1.0'
  gem 'spring-commands-rspec'
end

group :development do
  gem 'bullet', '>= 7.0.1'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'solargraph', '0.48.0'
  gem 'web-console', '4.2.0'
end

group :test do
  gem 'capybara', '3.38.0'
  gem 'guard', '2.18.0'
  gem 'mock_redis'
  gem 'rails-controller-testing', '1.0.5'
  gem 'selenium-webdriver', '4.8.3'
  gem 'webdrivers', '5.2.0'
end

gem 'redis', '~> 5.2'
gem 'retryable'
