import Head from "next/head";
import Link from "next/link";
import styles from '../styles/Home.module.css';

export async function getStaticProps() {
    try {
        const res = await fetch("http://localhost:3000/api/v1/posts");

        if (!res.ok) {
            throw new Error(`投稿の取得に失敗しました。${res.status}`);
        }

        const posts = await res.json();
        return {
            props: {
                posts,
            },
            revalidate: 60 * 60 * 24, // 24時間
        };
    } catch (error) {
        console.error("投稿の取得中にエラーが発生しました:", error);
        return {
            props: {
                posts: [],
                error: error.message,
            },
        };
    }
}

export default function Home({ posts, error }) {
    if (error) {
        return <div>Error loading posts: {error}</div>;
    }
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                {posts.map((post) => (
                    <div key={post.id} className={styles.postCard}>
                        <Link href={`/posts/${post.id}`}>
                            <a className={styles.postCardBox}>
                                <h2>{post.title}</h2>
                            </a>
                        </Link>
                        <p>{post.content}</p>
                        <button className={styles.editButton}>編集</button>
                        <button className={styles.deleteButton}>削除</button>
                    </div>
                ))}
            </div>
        </>
    )
}
