name: Run RSpec and RuboCop

on:
  push:
    branches:
      - feature

jobs:
  RSpec:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      db:
        image: mysql:8.0
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ROOT_HOST: "%"
        volumes:
          - db_data:/var/lib/mysql

      redis:
        image: redis:6.2
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 6379:6379

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Bundlerとgemをインストール
        working-directory: back
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Yarnをインストール
        working-directory: back
        run: yarn install --check-files

      - name: データベース設定ファイルをコピー
        working-directory: back
        run: cp config/database.yml.ci config/database.yml

      - name: Redisクライアントツールのインストール
        run: sudo apt-get install -y redis-tools

      - name: Redisの状態確認
        run: |
          for i in {1..10}; do
            redis-cli -h 127.0.0.1 ping && echo "Redis is up" && break
            echo "Waiting for Redis..."
            sleep 5
          done || { echo "Redis did not start"; exit 1; }

      - name: データベースの状態確認
        run: |
          for i in {1..10}; do
            mysqladmin ping -h 127.0.0.1 --silent && echo "MySQL is up" && break
            echo "Waiting for MySQL..."
            sleep 5
          done || { echo "MySQL did not start"; exit 1; }

      - name: データベースを作成およびマイグレーション
        working-directory: back
        run: |
          bundle exec rake db:create RAILS_ENV=test --trace
          bundle exec rake db:migrate RAILS_ENV=test --trace

      - name: RSpecを実行
        working-directory: back
        run: bundle exec rspec
        env:
          RAILS_ENV: test

  RuboCop:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Bundlerとgemをインストール
        working-directory: back
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: RuboCopを実行
        working-directory: back
        run: bundle exec rubocop
