name: Amazon ECSバックエンドデプロイ

on:
  push:
    branches: ["main"]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_REGION: ap-northeast-1
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BACKEND_CONTAINER_NAME: ${{ secrets.BACKEND_CONTAINER }}
  NGINX_CONTAINER_NAME: ${{ secrets.NGINX_CONTAINER }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  BACKEND_ECS_SERVICE: ${{ secrets.BACKEND_ECS_SERVICE }}
  IMAGE_TAG: ${{ github.sha }}

permissions:
  contents: read

jobs:
  deploy:
    name: バックエンドデプロイ
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: AWS認証情報の設定
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Amazon ECRへのログイン
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: バックエンドコンテナのイメージをビルドし、Amazon ECRにタグ付けしてプッシュ
        id: build-backend-image
        run: |
          docker build -t 504252798833.dkr.ecr.ap-northeast-1.amazonaws.com/tsunarhythm2-backend:${{ env.IMAGE_TAG }} -f ./back/Dockerfile.prod ./back
          docker push 504252798833.dkr.ecr.ap-northeast-1.amazonaws.com/tsunarhythm2-backend:${{ env.IMAGE_TAG }}
          echo "BACKEND_IMAGE=504252798833.dkr.ecr.ap-northeast-1.amazonaws.com/tsunarhythm2-backend:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Nginxコンテナのイメージをビルドし、Amazon ECRにタグ付けしてプッシュ
        id: build-nginx-image
        run: |
          docker build -t 504252798833.dkr.ecr.ap-northeast-1.amazonaws.com/tsunarhythm2-nginx:${{ env.IMAGE_TAG }} --no-cache -f ./back/nginx/Dockerfile ./back/nginx
          docker push 504252798833.dkr.ecr.ap-northeast-1.amazonaws.com/tsunarhythm2-nginx:${{ env.IMAGE_TAG }}
          echo "NGINX_IMAGE=504252798833.dkr.ecr.ap-northeast-1.amazonaws.com/tsunarhythm2-nginx:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: 環境変数の確認
        run: |
          echo "BACKEND_IMAGE=$BACKEND_IMAGE"
          echo "NGINX_IMAGE=$NGINX_IMAGE"

      - name: タスク定義内の変数を置き換え
        run: |
          sed -i 's|<BACKEND_IMAGE_TAG>|'"$BACKEND_IMAGE"'|g' back/task-definition.json
          sed -i 's|<NGINX_IMAGE_TAG>|'"$NGINX_IMAGE"'|g' back/task-definition.json

      - name: Amazon ECSタスク定義に新しいイメージIDを反映
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: back/task-definition.json
          container-name: ${{ env.BACKEND_CONTAINER_NAME }}
          image: $BACKEND_IMAGE

      - name: Amazon ECSタスク定義にNginxイメージIDを反映
        id: nginx-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: back/task-definition.json
          container-name: ${{ env.NGINX_CONTAINER_NAME }}
          image: $NGINX_IMAGE

      - name: Amazon ECSタスク定義のデプロイ
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.BACKEND_ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
