const RoomsData = [
  {
    id: 1,
    name: "普通のカフェ",
    members: 5,
    maxMembers: 5,
    image: "/StandardCafe.PNG",
    path: "/room/StandardCafe",
  },
  {
    id: 2,
    name: "シックなカフェ",
    members: 5,
    maxMembers: 5,
    image: "/CalmCafe.PNG",
    path: "/room/CalmCafe",
  },
  {
    id: 3,
    name: "宇宙空間",
    members: 5,
    maxMembers: 5,
    image: "/Universe.PNG",
    path: "/room/Universe",
  },
  {
    id: 4,
    name: "額縁ビーチ",
    members: 1,
    maxMembers: 1,
    image: "/Beach.jpg",
    path: "/room/Beach",
  },
  {
    id: 5,
    name: "さわたの部屋",
    members: 4,
    maxMembers: 5,
    image: "/SawataRoom.PNG",
    path: "/room/SawataRoom",
  },
  {
    id: 6,
    name: "もくもく作業部屋1",
    members: 1,
    maxMembers: 5,
    image: "/MokumokuRoom1.PNG",
    path: "/room/MokumokuRoom1",
  },
  {
    id: 7,
    name: "もくもく作業部屋2",
    members: 0,
    maxMembers: 6,
    image: "/MokumokuRoom2.PNG",
    path: "/room/MokumokuRoom2",
  },
  {
    id: 8,
    name: "もくもく作業部屋3",
    members: 3,
    maxMembers: 7,
    image: "/MokumokuRoom3.PNG",
    path: "/room/MokumokuRoom3",
  },
  {
    id: 9,
    name: "もくもく作業部屋4",
    members: 10,
    maxMembers: 10,
    image: "/MokumokuRoom4.PNG",
    path: "/room/MokumokuRoom4",
  },
  {
    id: 10,
    name: "さわたの部屋2",
    members: 4,
    maxMembers: 4,
    image: "/SawataRoom2.PNG",
    path: "/room/SawataRoom2",
  },
];

export default RoomsData;
